### ISSUE TITLE
Character Controller / Treasure Box - FREEZE

### ISSUE THREAD

**Issue by Yoshgunn** [JayXon/SSW800#5]
The Player should freeze when they encounter a TreasureBox. That way they can focus on the panel in front of them and the Player won't move unexpectedly.

The Player should unfreeze when they close the TreasureBox.

**Comment by Yoshgunn** [comment]
This issue has been worked on, but the fix is far from stable.

First of all, I used two different scripts for locking input and unlocking input. Let me explain why. The TreasureBox receives the collision so it makes sense to lock input there. But the Question receives the close event so it makes sense to unlock input there.

The one silver lining is the input functions on Player_Input work fine and don't need to be changed. What needs to be fixed is how we call them - what can we rely on to always make sense in every possible game scenario?

**Comment by JayXon** [comment]
I don't know what went wrong but freeze is not working properly. The player begins to rotate after freeze.

**Comment by Yoshgunn** [comment]
Yeah it's pretty hilarious. I'm not sure what it is either. LOL it would be a good punishment for players who get it incorrect! We can look into this at our meeting.

**Comment by Yoshgunn** [comment]
The player no longer rotates when colliding with a Treasure Box. The box passes a reference successfully.

He still skids though, not sure why. Added friction to slow him down.
